#include "atest.h"
#include <stdio.h>
#include <math.h>

void my_test_shutdown_func(void){
    // instead of printf(....) consider to use alogf() it's more structural and contains line source:lnumber reference
    atlogf("atest_shutdown()\n");
}
/* Initialializers called for every test */
ATEST_SETUP_F(void)
{
    atlogf("atest_setup()\n");
    //return NULL;   // if no shutdown logic needed
    return &my_test_shutdown_func;  // return pointer to void some_shutdown_func(void)
}

ATEST_F(assert_with_formatting){
    int exp = 1;
    int act = 0;

    atassertf(exp == act, "expected: %d != actual: %d", exp, act);
    return NULL; // Every ATEST_F() must return NULL to succeed! 
}

ATEST_F(assert_eq_strings_null_expected)
{
    atassert_eqs(NULL, NULL);
    atassert_eqs("b", NULL);
    return NULL; // Every ATEST_F() must return NULL to succeed!
}
ATEST_F(assert_eq_strings_null_actual)
{
    atassert_eqs(NULL, NULL);
    atassert_eqs(NULL, "b");
    return NULL; // Every ATEST_F() must return NULL to succeed!
}
ATEST_F(assert_eq_strings)
{
    atassert_eqs("b", "b");
    atassert_eqs("b", "axb");
    atassert_eqs(NULL, NULL);
    atassert_eqs("b", NULL);
    atassert_eqs("b", NULL);
    return NULL; // Every ATEST_F() must return NULL to succeed!
}


ATEST_F(assert_eq_float)
{
    atassert(INFINITY == INFINITY);
    atassert(-INFINITY == -INFINITY);
    atassert(-INFINITY != INFINITY);
    atassert_eqf(0.0, 0.0);
    atassert_eqf(INFINITY, INFINITY);
    atassert_eqf(-INFINITY, -INFINITY);
    atassert(NAN != NAN);  // Originally NAN != NAN
    //atassert(NAN == NAN);  // will fail!
    atassert_eqf(NAN, NAN);  //atassert_eqf NAN == NAN, assert shoul pass 
    atassert_eqf(1.0/3.0, 1.0/3.0);
    atassert_eqf(1.0/3.0, 0.3333333);  // This one passes float epsilon test
    atassert_eqf(1.0/3.0, 0.333333);   // This one won't
    return NULL; // Every ATEST_F() must return NULL to succee!
}
ATEST_F(assert_eq_int)
{
    atassert_eqi(0, 0);
    atassert_eqi((int)(pow(3, 2)), 8);
    return NULL; // Every ATEST_F() must return NULL to succeed!
}

ATEST_F(assert_passed)
{
    atassert(1==1);
    return NULL; // Every ATEST_F() must return NULL to succeed!
}

ATEST_F(assert_fails_with_some_logging)
{
    atlogf("simple msg\n");
    atlogf("HI this test is gonna fail, because %d != %d!\n", 1, 0);

    atassert(1 == 0);
    return NULL; // Every ATEST_F() must return NULL to succeed! 
}

int main(int argc, char *argv[])
{
    //FILE * f = fopen("test.log", "w");
    //__ATestContext.out_stream = f;
    __ATestContext.verbosity = 3;
    ATEST_PARSE_MAINARGS(argc, argv);

    ATEST_PRINT_HEAD();

    // <ATEST_RUNS>   -- do not replace to make 'atest' utility automatic test updates
    ATEST_RUN(assert_with_formatting);
    ATEST_RUN(assert_eq_strings_null_expected);
    ATEST_RUN(assert_eq_strings_null_actual);
    ATEST_RUN(assert_eq_strings);
    ATEST_RUN(assert_eq_float);
    ATEST_RUN(assert_eq_int);
    ATEST_RUN(assert_passed);
    ATEST_RUN(assert_fails_with_some_logging);
    // ^^^^ this block is automatically generated by 'atest' utility

    ATEST_PRINT_FOOTER();
    //fclose(f);
    
    return ATEST_EXITCODE();
}
