#include "atest.h"
//
// IMPORTANT: inlcuding .c allows testing static functions!
//            also no need to include all headers/sources except testlib2.c in Makefile
//
#include "../src/testlib.c"
// testlib.add() uses testlib2.mul() inside
//   Lets make fake function!
//   IMPORTANT: don't include testlib2.h(.c) here or in linker when using fff.h for this lib!

// https://github.com/meekrosoft/fff
#include "fff.h"

DEFINE_FFF_GLOBALS;

// fake testlib2.c: int mul(int a, int b)
//    don't include testlib2.h or include into linker
FAKE_VALUE_FUNC(int, mul, int, int);



/* Initialializers called for every test */
ATEST_SETUP_F(void)
{
    RESET_FAKE(mul);
    FFF_RESET_HISTORY();
    return NULL;   // if no shutdown logic needed
}

ATEST_F(original_mul_is_not_available)
{
    // Original `mul` is completely irrelevant to this module
    //    mul retval is set to 0 (macro default)
    // add => 2+3 + testlib2.mul(2, 3) -> without fake 5+6=11
    // with fake mul=>0 -> 5
    atassertf(add(2, 3) == 7, "you must always set mul.return_val for fake functions, got result %d", add(2,3));

    return NULL; // Every ATEST_F() must return NULL to succeed!
}

ATEST_F(fake_mul_mock)
{
    mul_fake.return_val = 2;
    // add => 2+3 + testlib2.mul(2, 3) -> without fake 5+6=11
    // with fake mul=>2 -> 5+2=7
    atassertf(add(2, 3) == 7, "actual: %d != 7", add(2,3));

    return NULL; // Every ATEST_F() must return NULL to succeed!
}

int main(int argc, char *argv[])
{
    //FILE * f = fopen("test.log", "w");
    //__ATestContext.out_stream = f;
    __ATestContext.verbosity = 3;

    ATEST_PARSE_MAINARGS(argc, argv);
    ATEST_PRINT_HEAD();

    // <ATEST_RUNS>   -- do not replace to make 'atest' utility automatic test updates
    ATEST_RUN(original_mul_is_not_available);
    ATEST_RUN(fake_mul_mock);
    // ^^^^ this block is automatically generated by 'atest' utility

    ATEST_PRINT_FOOTER();
    //fclose(f);
    
    return ATEST_EXITCODE();
}
